{
  "pipeline_settings": {
    "quality_threshold": 95.0,
    "min_coverage": 80.0,
    "max_missing_data": 5.0,
    "batch_size": 50
  },
  "analysis_parameters": {
    "mutation_types": [
      "SNP",
      "indel"
    ],
    "resistance_databases": [
      "CARD",
      "ResFinder"
    ],
    "gene_families": [
      "bla",
      "aac",
      "tet",
      "gyr",
      "par"
    ]
  },
  "output_options": {
    "format": [
      "json",
      "csv",
      "html"
    ],
    "include_plots": true,
    "detailed_logs": true,
    "compress_results": false
  },
  "system_resources": {
    "max_processes": 4,
    "memory_limit": "8GB",
    "temp_dir": "./tmp"
  }
}