name: mutationscan
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - pip
  - pytest
  - snakemake-minimal>=7.32.4
  - blast
  - openmm
  - pdbfixer
  - smina
  - pandas>=2.0.0
  - biopython>=1.81
  - networkx>=3.0
  - matplotlib>=3.7.0
  - pyyaml>=6.0
  - requests>=2.31.0
  - rdkit
  - gemmi
  - pip:
      - meeko>=0.6
